### ISSUE TITLE
How hard would it be to add "You obtain X gils" and stuff like that in the log ?

### ISSUE THREAD

**Issue by Tashiro64** [cadaeix/XIVLogger#16]
How hard would it be to add "You obtain X gils" or "Name receives 2 <item>" and stuff like that in the log? They don't seem to be logged, or maybe i'm just dumb?
OItherwise It would be so nice and would save my life with the project I have if it was possible, but I don't know, I looked a bit in the code but i'm not very used to this structure and language

**Comment by Infiziert90** [comment]
I recommend you get the plugin called "ChatTyper"
This plugin allows you to the chat channel name of your message, and with that you can pick this chat channel for XIVLogger to save

Or you get a plugin like Currency Tracker, which tracks currencies and allows you to export histories

**Comment by Tashiro64** [comment]
oh Currency Tracker does exactly what I want! it saves everything in a .txt that I can fetch data from for my project! thx a lot!
