### ISSUE TITLE
Autosave log is overwritten to blank when game crashes

### ISSUE THREAD

**Issue by liamont** [cadaeix/XIVLogger#6]
When the game crashes, the autosave file is written over to blank, with only "Autosave" in the file. This means that all that was logged previously was lost, which defeats the purpose of using an autosave to keep logs in case of crashes.

**Comment by iRobsie** [comment]
I just recently submitted feedback to this via in-game, but chiming in on this, I'm experiencing this issue as well, but also when I'm exiting the game normally. It's not a 100% of the time deal, but I'd say 90% of the time when I close my game, my autosave log is overwritten completely just like liamont's.

**Comment by BlueSkia** [comment]
FYI, this happens also when you get kicked back to the title screen for some reason, i.e. network issues and you lose connection to the server, without actually crashing out.
